apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice2
  template:
    metadata:
      labels:
        app: microservice2
    spec:
      containers:
        - image: clageleeesiee/microservice2:1
          imagePullPolicy: IfNotPresent
          name: microservice2
      restartPolicy: Always
