apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice1
  template:
    metadata:
      labels:
        app: microservice1
    spec:
      containers:
        - image: clageleeesiee/microservice1:2
          imagePullPolicy: IfNotPresent
          name: microservice1
      restartPolicy: Always
