apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice2
  name: microservice2
spec:
  ports:
    - nodePort: 30945
      port: 4001
      protocol: TCP
      targetPort: 8080
  selector:
    app: microservice2
  type: LoadBalancer