apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice1
  name: microservice1
spec:
  ports:
    - nodePort: 30945
      port: 4000
      protocol: TCP
      targetPort: 8080
  selector:
    app: microservice1
  type: LoadBalancer